FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy project files
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Install cron
RUN apt-get update && apt-get install -y cron

# Create log file (IMPORTANT)
RUN touch /var/log/cron.log

# Copy cron file
COPY crontab /etc/cron.d/updater-cron

# Give correct permissions
RUN chmod 0644 /etc/cron.d/updater-cron

# Register cron job
RUN crontab /etc/cron.d/updater-cron

# Start cron in foreground
CMD ["cron", "-f"]